### ISSUE TITLE
Uncaught Error: Call to a member function log() on null

### ISSUE THREAD

**Issue by sicet7** [clerkio/clerk-magento2#34]
Version: 3.4.1

```
PHP Fatal error:  Uncaught Error: Call to a member function log() on null in vendor/clerk/magento2/Controller/AbstractAction.php:338
Stack trace:
#0 vendor/magento/framework/App/Action/Action.php(108): Clerk\Clerk\Controller\AbstractAction->execute()
#1 vendor/clerk/magento2/Controller/AbstractAction.php(160): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#2 vendor/magento/framework/Interception/Interceptor.php(58): Clerk\Clerk\Controller\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http))
#3 vendor/magento/framework/Interception/Interceptor.php(138): Clerk\Clerk\Controller\Customer\Index\Interceptor->___callParent('dispatch', Array)
#4 vendor/magento/framework/Interception/Interceptor.php(153): Clerk\Clerk\Contro in vendor/clerk/magento2/Controller/AbstractAction.php on line 338
```

i see that you have fixed this issue in the new major version but im not sure that it's a good idea to restrict a fix for a fatel error to going to a now major verison, so maybe we can get a 3.4.2 version which fixes this issue in the same manor as the 4.0.0 version does.

**Comment by Kimpansen** [comment]
This question is quite old now but, the move from 3.4.1 to 4.0.0 fixed many issues and was deemed a necessary step to ensure quality.
